version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm i
  build:
    commands:
      - echo Build Stage started on `date`
      - echo Running test cases
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: aws-code-star-sample